# Generated by Django 3.0.3 on 2020-02-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal_vault', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='payment_method',
            new_name='Payment_method',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='input_date',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'income'), ('Expenses', 'Expenses')], default='Expense ', max_length=60, verbose_name='type_of_trans'),
        ),
    ]
